FROM koo5/ubuntu
ARG APPDIR
ARG APPPATH
ENV APPDIR=${APPDIR}
ENV APPPATH=${APPPATH}




RUN apt-get install -y nodejs npm
RUN pip install "watchdog==3.0.0"



RUN echo "ENVxx:" "$APPDIR" "$APPPATH"




USER myuser:myuser
WORKDIR $APPPATH
COPY  --chown=myuser:myuser  $APPDIR/package.json .
COPY  --chown=myuser:myuser  $APPDIR/package-lock.json .

RUN chown -vR myuser:myuser $APPPATH

RUN pwd
RUN ls -thrlsa
RUN echo $USER

RUN npm install



CMD "./start.sh"
ENV HC="curl http://127.0.0.1:17790/health" 



#start interval is the time between health checks during the start period. This option requires Docker Engine version 25.0 or later.
HEALTHCHECK --interval=2s --timeout=600s CMD { test -f /healthcheck/ok && echo -n "sleep.." && sleep 555 && echo -n "hc..>> " && /bin/sh -c '/bin/sh -c "$HC"' && echo -n " <<..hc passed." ; } || { echo -n "hc..>> " && echo -n "$HC" && echo -n " <<... " && /bin/sh -c '/bin/sh -c "$HC"' && echo -n " << first hc passed." && touch /healthcheck/ok && echo " flag stored." ; } 
