---
demo7778:
   defaults:
      type: exec
   services:   
      - name: internal_services
        exec: ./run.sh
        args: "17778"
        dir: ./internal_services
      - name: frontend_server
        exec: bash
        args: -c "env MY_SERVICES_SERVER_URL=\"http://localhost:17778\" ./run.sh 0.0.0.0:7778"
        dir: ./frontend_server

demox:
   defaults:
      type: exec
   services:   
      - name: frontend_server
        exec: bash
        args: -c "echo -e \"xxx\n\nyyy\";sleep 1"
        dir: ./frontend_server

