# todo check out http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#supervisor http://supervisord.org/
# this config file is for a "service manager" program that isn't available publicly yet

---
demo7788:
   defaults:
      type: exec
   services:   
      - name: celery_worker
        dir: ./internal_workers
        exec: bash
        args: -c "env PYTHONUNBUFFERED=true CELERY_QUEUE_NAME=q7788 ./run.sh  -n w7788 --loglevel=info"

      - name: internal_services
        dir: ./internal_services
        exec: bash
        args: -c "env PYTHONUNBUFFERED=true ./run.sh 17788"

      - name: frontend_server
        dir: ./frontend_server
        exec: bash
        args: -c "env PYTHONUNBUFFERED=true CELERY_QUEUE_NAME=q7788 MY_SERVICES_SERVER_URL=\"http://localhost:17788\" ./run_prod.sh 0.0.0.0:7788"
        

demo7778:
   defaults:
      type: exec
   services:   
      - name: internal_services
        exec: ./run.sh
        args: "17778"
        dir: ./internal_services
      - name: frontend_server
        exec: bash
        args: -c "env MY_SERVICES_SERVER_URL=\"http://localhost:17778\" ./run.sh 0.0.0.0:7778"
        dir: ./frontend_server

demo7768:
   services:   
      - name: celery_worker
        dir: ./internal_workers
        exec: bash
        args: -c "env PYTHONUNBUFFERED=true CELERY_QUEUE_NAME=q7768 ./run.sh  -n w7768 --loglevel=info"

      - name: internal_services
        dir: ./internal_services
        exec: bash
        args: -c "env PYTHONUNBUFFERED=true ./run.sh 17768"
        
        #frontend_server is through mod_wsgi, internal services port is set in endpoints_gateway/views.py 
        # mod_wsgi is compiled with ./configure --with-python=/home/demo/7768/venv/bin/python3 and wired up from /etc/apache2/sites-enabled/..

        
