# todo check out http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#supervisor http://supervisord.org/
# this config file is for a "service manager" program that isn't available publicly yet

---
demo7778:
   defaults:
      type: exec
   services:   
      - name: internal_services
        exec: ./run.sh
        args: "17778"
        dir: ./internal_services
      - name: frontend_server
        exec: bash
        args: -c "env MY_SERVICES_SERVER_URL=\"http://localhost:17778\" ./run.sh 0.0.0.0:7778"
        dir: ./frontend_server

demo7768:
   defaults:
      type: exec
   services:   
      - name: internal_services
        exec: ./run.sh
        args: "17768"
        dir: ./internal_services
        
        #frontend_server is through mod_wsgi, internal services port is defaulted in endpoints_gateway/views.py 
        # mod_wsgi is compiled with ./configure --with-python=/home/demo/7768/venv/bin/python3 and wired up from /etc/apache2/sites-enabled/..

#fixme      - name: celery_worker
#        exec: ../venv/bin/celery
#        args: -E -A c worker --loglevel=debug
#        dir: ./server_root
        
