version: '3.7'

services:


  caddy:
    image: caddy:2-alpine
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/Caddyfile_auth:/etc/caddy/Caddyfile_auth
      - caddy_data:/data
      - caddy_config:/config


  apache:
    image: koo5/apache${PP}:latest
    networks:
      - frontend
      - backend
    hostnet_ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      #- ./../sources/apache/conf/ /usr/local/apache2/conf/
      #- ./../sources/apache/conf/httpd.conf /usr/local/apache2/conf/httpd.conf
      - "/etc/localtime:/etc/localtime:ro"
      - tmp:/usr/local/apache2/htdocs/tmp/
      - ./../sources/static/:/usr/local/apache2/htdocs/static/


  frontend:
    image: koo5/frontend${PP}:latest
    environment:
      DJANGO_ARGS: "${DJANGO_ARGS}"
      DJANGO_SETTINGS_MODULE: "frontend_server.settings_prod"
      RABBITMQ_URL: "rabbitmq:5672"
      SECRETS_DIR: /run/secrets/
    volumes:
      - tmp:/app/server_root/tmp
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend
    hostnet_ports:
      - 7788
    depends_on:
      - redis
      - services
      - workers
      - rabbitmq
      - postgres
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - SECRET__REDIS_HOST
      - DJANGO_SECRET_KEY
      - AGRAPH_SECRET_HOST
      - AGRAPH_SECRET_PORT
      - AGRAPH_SUPER_USER
      - AGRAPH_SUPER_PASSWORD


  workers:
    image: koo5/workers${PP}:latest
    environment:
      SECRET__INTERNAL_SERVICES_SERVER_URL: "http://services:17788"
#      SECRET__CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      DETERMINANCY_CHECKER__USE__ENFORCER: "true"
      RABBITMQ_URL: "rabbitmq:5672"
    volumes:
      - tmp:/app/server_root/tmp
      - cache:/app/cache
      - ./../tests:/app/tests
      - "/etc/localtime:/etc/localtime:ro"
      # for gtrace:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    networks:
      - backend
    depends_on:
      - redis
      - services
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - SECRET__REDIS_HOST
      - AGRAPH_SECRET_HOST
      - AGRAPH_SECRET_PORT
      - AGRAPH_SUPER_USER
      - AGRAPH_SUPER_PASSWORD


  services:
    image: koo5/services${PP}:latest
    environment:
      DJANGO_ARGS: "${DJANGO_ARGS}"
      RABBITMQ_URL: "rabbitmq:5672"
    volumes:
      - tmp:/app/server_root/tmp
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend
    hostnet_ports:
      - 17788
    depends_on:
      - redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any


  redis:
    image: redis:6-alpine
    networks:
      - backend
    hostnet_ports:
      - 6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  agraph:
    image: koo5/agraph${PP}:latest
    networks:
    - backend
    - frontend
    hostnet_ports:
      - 10035
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        # https://docs.docker.com/compose/compose-file/compose-file-v3/
        condition: any
        delay: "240s"
    secrets:
      - AGRAPH_SUPER_USER
      - AGRAPH_SUPER_PASSWORD
    environment:
      AGRAPH_SUPER_PASSWORD_FILE: /run/secrets/AGRAPH_SUPER_PASSWORD
      AGRAPH_SUPER_USER_FILE: /run/secrets/AGRAPH_SUPER_USER
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "agdata:/agraph/data"
      - "agconfig:/agraph/etc"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 2096000000
    #shm_size: "1G" # not supported in swarm
    #finishme: use low-memory configuration


  rabbitmq:
    image: rabbitmq:management
    networks:
      - backend
    hostnet_ports:
      - 5672
    deploy:
      restart_policy:
        condition: any
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - rabbitmq:/var/lib/rabbitmq


  postgres:
    image: bitnami/postgresql:14
    networks:
      - backend
    hostnet_ports:
      - 5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_POSTGRES_PASSWORD=""
      - POSTGRESQL_DATABASE=remoulade
      - POSTGRESQL_USERNAME=remoulade
    deploy:
      replicas: 1
      restart_policy:
        condition: any


  superbowl:
    image: koo5/super-bowl:latest
    networks:
      - backend
    hostnet_ports:
      - 1238
    environment:
      SUPERBOWL_WEBSERVER_PORT: 1238
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  remoulade-api:
    image: koo5/remoulade-api${PP}:latest
    networks:
      - backend
    hostnet_ports:
      - 5000
    environment:
      RABBITMQ_URL: "rabbitmq:5672"
    deploy:
      replicas: 1
      restart_policy:
        condition: any


#  flower:
#    image: koo5/flower${PP}:latest
#    networks:
#      - backend
#    hostnet_ports:
#      - 5555
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 2
#        delay: 10s
#      restart_policy:
#        condition: any
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"



networks:
  frontend:
    attachable: true
  backend:
    #driver: overlay
    attachable: true
  hostnet:
    external: true
    name: host

volumes:
  tmp:
  cache:
  agdata:
  agconfig:
  rabbitmq:
  caddy_data:
  caddy_config:
  postgresql_data:

