version: '3.7'

services:

  agraph:
    #finishme: use low-memory configuration 
    image: franzinc/agraph:v7.0.0
    networks:
    - host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "agdata:/agraph/data"
      - "agconfig:/agraph/etc"


      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 2096000000
    #shm_size: "1G"


    ports:
      - 10036:10035

  rabbitmq:
    image: rabbitmq
    networks:
    - host
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  frontend-server:
    image: koo5/frontend-server:latest
    environment:
      SECRET__INTERNAL_SERVICES_SERVER_URL: "http://internal-services:17788"
      SECRET__CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - tmp:/app/server_root/tmp
      - "/etc/localtime:/etc/localtime:ro"
    networks:
    - host
    depends_on:
      - rabbitmq
      - internal-services
      - internal-workers
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    ports:
      - 7788:7788


  internal-services:
    image: koo5/internal-services:latest
    volumes:
      - tmp:/app/server_root/tmp
      - "/etc/localtime:/etc/localtime:ro"
    networks:
    - host

    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    ports:
      - 17788:17788

  internal-workers:
    image: koo5/internal-workers:latest
    environment:
      SECRET__INTERNAL_SERVICES_SERVER_URL: "http://internal-services:17788"
      SECRET__CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      DETERMINANCY_CHECKER__USE__ENFORCER: "true"
      DISPLAY: "${DISPLAY}"
    volumes:
      - tmp:/app/server_root/tmp
      - cache:/app/cache
      - "/etc/localtime:/etc/localtime:ro"

      # for gtrace:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      
      # for development:
      - ".:/app/sources"
      
    networks:
    - host

    depends_on:
      - rabbitmq
      - internal-services
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any

networks:
  host:
  
volumes:
  tmp:
  cache:
  agdata:
  agconfig:
