networks:
  backend:
    attachable: true
  frontend: null
  hostnet:
    external: true
    name: host
secrets:
  AGRAPH_SECRET_HOST:
    file: ../secrets/AGRAPH_SECRET_HOST
  AGRAPH_SECRET_PORT:
    file: ../secrets/AGRAPH_SECRET_PORT
  AGRAPH_SUPER_PASSWORD:
    file: ../secrets/AGRAPH_SUPER_PASSWORD
  AGRAPH_SUPER_USER:
    file: ../secrets/AGRAPH_SUPER_USER
  DJANGO_SECRET_KEY:
    file: ../secrets/DJANGO_SECRET_KEY
services:
  agraph:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 10s
        parallelism: 1
    environment:
      AGRAPH_SUPER_PASSWORD_FILE: /run/secrets/AGRAPH_SUPER_PASSWORD
      AGRAPH_SUPER_USER_FILE: /run/secrets/AGRAPH_SUPER_USER
    image: koo5/agraph${PP}:latest
    networks:
    - backend
    - frontend
    ports:
    - 100${PP}:10035
    secrets:
    - AGRAPH_SUPER_USER
    - AGRAPH_SUPER_PASSWORD
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - agdata:/agraph/data
    - agconfig:/agraph/etc
    - target: /dev/shm
      tmpfs:
        size: 2096000000
      type: tmpfs
  frontend-server:
    depends_on:
    - rabbitmq
    - internal-services
    - internal-workers
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: any
    environment:
      SECRET__CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      SECRET__INTERNAL_SERVICES_SERVER_URL: http://internal-services:17788
    image: koo5/frontend-server${PP}:latest
    networks:
    - backend
    - frontend
    ports:
    - 77${PP}:7788
    secrets:
    - DJANGO_SECRET_KEY
    - AGRAPH_SECRET_HOST
    - AGRAPH_SECRET_PORT
    - AGRAPH_SUPER_USER
    - AGRAPH_SUPER_PASSWORD
    volumes:
    - tmp:/app/server_root/tmp
    - /etc/localtime:/etc/localtime:ro
    - .:/app/sources
  internal-services:
    depends_on:
    - rabbitmq
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 10s
        parallelism: 2
    image: koo5/internal-services${PP}:latest
    networks:
    - backend
    volumes:
    - tmp:/app/server_root/tmp
    - /etc/localtime:/etc/localtime:ro
    - .:/app/sources
  internal-workers:
    depends_on:
    - rabbitmq
    - internal-services
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 10s
        parallelism: 2
    environment:
      DETERMINANCY_CHECKER__USE__ENFORCER: 'true'
      DISPLAY: ${DISPLAY}
      SECRET__CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      SECRET__INTERNAL_SERVICES_SERVER_URL: http://internal-services:17788
    image: koo5/internal-workers${PP}:latest
    networks:
    - backend
    ports:
    - 123${PP}:1234
    secrets:
    - AGRAPH_SECRET_HOST
    - AGRAPH_SECRET_PORT
    - AGRAPH_SUPER_USER
    - AGRAPH_SUPER_PASSWORD
    volumes:
    - tmp:/app/server_root/tmp
    - cache:/app/cache
    - /etc/localtime:/etc/localtime:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - .:/app/sources
    - ./swipl/xpce:/root/.config/swi-prolog/xpce
  rabbitmq:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 10s
        parallelism: 2
    image: rabbitmq
    networks:
    - backend
    volumes:
    - /etc/localtime:/etc/localtime:ro
version: '3.7'
volumes:
  agconfig: null
  agdata: null
  cache: null
  tmp: null
