# fly.toml app configuration file generated for robust-worker-dark-pond-3497-dry-shape-7521-nameless-moon-5529 on 2024-02-14T02:54:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'robust-worker-dark-pond-3497-dry-shape-7521-nameless-moon-5529'
primary_region = 'mad'

[build]
  dockerfile = 'worker/dddd'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
