# fly.toml app configuration file generated for robust-worker-dark-pond-3497-dry-shape-7521-nameless-moon-5529-long-river-3075-frosty-waterfall-3384-rough-pond-5981-young-pine-6329-young-log-7428-cool-firefly-4571-winter-firefly-6942 on 2024-02-14T16:35:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'robust-worker-dark-pond-3497-dry-shape-7521-nameless-moon-5529-long-river-3075-frosty-waterfall-3384-rough-pond-5981-young-pine-6329-young-log-7428-cool-firefly-4571-winter-firefly-6942'
primary_region = 'mad'

[build]
  dockerfile = 'worker/dddd'

[checks]
  [checks.name_of_your_http_check]
    port = 1111
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
