site_name: Robust
theme:
  name: readthedocs  
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  collapse_navigation: false
  #titles_only: true
  
    

extra_css:
  - style.css


plugins:
#  - search
  - awesome-pages
  - git-revision-date-localized


markdown_extensions:
  - toc:
      baselevel: 2
      

