site_name: Robust


theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  collapse_navigation: false
  #titles_only: true
  max_toc_depth: 4
  
    

extra_css:
  - style.css


plugins:
#  - search
  - awesome-pages
  - git-revision-date-localized


#markdown_extensions:
#  - toc:
#      baselevel: 2
#      
#
