on: [ push ]

env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  up:
    if: github.repository == 'koo5/accounts-assessor'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: docker_scripts/first_run.sh
      - run: docker_scripts/init_configs.sh
      - run: docker_scripts/up.sh


