name: up

on: [ push, pull_request ]

env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: docker_scripts/first_run0.sh
      - run: docker_scripts/first_run1.sh
      - run: docker_scripts/first_run1b.sh
      - run: docker_scripts/first_run2.sh
      - run: cd docker_scripts; ./up.py
